import type { Asset } from "../types/game";

export const assets: Asset[] = [
  {
    id: "macbook",
    slug: "macbook",
    name: "MacBook",
    category: "physical",
    owner: "kirill",
    status: "active",
    conditionPct: 91,
    moneyValueUsd: 1500,
    utilityScore: 1240,
    purpose: "Primary founder workstation for product decisions, writing and ecosystem operations.",
    realFunction: ["Product planning", "Content review", "Telegram/community ops", "Founder strategy"],
    gameFunction: ["Boosts Vision", "+5% Knowledge from Atlas missions", "Improves Reality Update frequency"],
    connectedProductIds: ["atlasrepo", "want2view", "youtube"],
    connectedSubscriptionIds: ["ChatGPT/Codex", "GitHub", "Figma"],
    producedResource: "knowledge",
    outputModifier: 5,
    currentLoadPct: 58,
    visualState: "Screen lit, Kirill nearby",
    upgradePath: [
      { id: "monitor", title: "External monitor", requirement: "Reality Update", effect: "+8 Vision", status: "available" },
      { id: "backup", title: "Backup drive", requirement: "Future funding", effect: "Safer content ops", status: "locked" }
    ],
    realityUpdates: ["Season 0: Founder workstation registered in Our Room."],
    fundingRelationship: "Not a first funding object; appears in Reality Updates."
  },
  {
    id: "mac-mini",
    slug: "mac-mini",
    name: "Mac mini",
    category: "physical",
    owner: "ecosystem",
    status: "active",
    conditionPct: 86,
    moneyValueUsd: 700,
    utilityScore: 1420,
    purpose: "Dedicated render and vertical-video device for services, social edits and Kirill's content pipeline.",
    realFunction: ["Renders vertical videos", "Exports social clips", "Supports service promo generation", "Keeps main workstation free"],
    gameFunction: ["Render Node generator", "+140 Compute/hour when bought in Factory", "Unlocks video-service shop perks later"],
    connectedProductIds: ["youtube", "want2view", "atlasrepo"],
    connectedSubscriptionIds: ["Video tools", "Cloud storage", "API credits"],
    producedResource: "compute",
    outputModifier: 12,
    currentLoadPct: 73,
    visualState: "Active node with subtle fan light",
    upgradePath: [
      { id: "ssd", title: "Add external SSD", requirement: "Funding campaign", effect: "+6% Compute output", status: "funding" },
      { id: "render", title: "Connect render queue", requirement: "Video Agent milestone", effect: "+Video Credits later", status: "locked" }
    ],
    realityUpdates: ["Reality Update #04: Mac mini planned as a dedicated vertical video render node."],
    fundingRelationship: "Crowdfunding preview target: $1,000. Support grants mock FBC credit only, not equity, profit share or token rights."
  },
  {
    id: "old-dell",
    slug: "old-dell",
    name: "Old Dell",
    category: "physical",
    owner: "ecosystem",
    status: "degraded",
    conditionPct: 43,
    moneyValueUsd: 150,
    utilityScore: 260,
    purpose: "Legacy research node for experiments, backup tasks and old-school infrastructure stories.",
    realFunction: ["Runs experiments", "Tests open-source tools", "Backup research device"],
    gameFunction: ["Low-efficiency research node", "+2 Knowledge/hour when revived", "Satisfying upgrade path"],
    connectedProductIds: ["atlasrepo"],
    connectedSubscriptionIds: ["GitHub", "Open-source tooling"],
    producedResource: "knowledge",
    outputModifier: 2,
    currentLoadPct: 88,
    visualState: "Overloaded with flickering terminal",
    upgradePath: [
      { id: "clean", title: "Clean disk", requirement: "20 Knowledge", effect: "Stabilize node", status: "available" },
      { id: "linux", title: "Install Linux", requirement: "Atlas Rank 2", effect: "Legacy Research Node", status: "locked" }
    ],
    realityUpdates: ["Season 0: Old Dell discovered as potential research node."],
    fundingRelationship: "Best used as a YouTube/Reality Update object."
  },
  {
    id: "atlasrepo-knowledge-base",
    slug: "atlasrepo-knowledge-base",
    name: "AtlasRepo Knowledge Base",
    category: "digital",
    owner: "ecosystem",
    status: "active",
    utilityScore: 1480,
    purpose: "Structured repository research, lessons, prompts and implementation notes that turn discovery into teachable systems.",
    realFunction: ["Stores curated repo research", "Feeds lessons", "Supports YouTube scripts", "Documents build decisions"],
    gameFunction: ["Unlocks Atlas missions", "+10% Knowledge rewards later", "Creates Contribution events"],
    connectedProductIds: ["atlasrepo", "youtube"],
    connectedSubscriptionIds: ["GitHub", "Notion", "Codex"],
    producedResource: "knowledge",
    outputModifier: 10,
    currentLoadPct: 61,
    visualState: "Indexed library with active scan cursor",
    upgradePath: [
      { id: "taxonomy", title: "Add repo taxonomy", requirement: "Atlas Rank 2", effect: "Cleaner mission generation", status: "available" },
      { id: "lesson-pack", title: "Publish first lesson pack", requirement: "Content milestone", effect: "Reward Vault utility later", status: "locked" }
    ],
    realityUpdates: ["Season 0: First Scan writes local contribution history from AtlasRepo research."],
    fundingRelationship: "Can justify lesson access rewards after real entitlement checks exist."
  },
  {
    id: "subscription-stack",
    slug: "subscription-stack",
    name: "Subscription Stack",
    category: "subscription",
    owner: "kirill",
    status: "expiring",
    monthlyCostUsd: 180,
    utilityScore: 760,
    purpose: "The recurring tool layer needed to keep the ecosystem building: AI tools, hosting, design and repository services.",
    realFunction: ["Pays for AI/dev tools", "Keeps hosting online", "Supports design/prototype work", "Maintains repository workflow"],
    gameFunction: ["Adds upkeep pressure", "Explains support goals", "Can unlock promo-code missions later"],
    connectedProductIds: ["atlasrepo", "want2view", "fabricbot"],
    connectedSubscriptionIds: ["ChatGPT/Codex", "GitHub", "Figma", "Hosting"],
    producedResource: "compute",
    outputModifier: 4,
    currentLoadPct: 79,
    visualState: "Recurring invoices stacked on a terminal",
    upgradePath: [
      { id: "audit", title: "Audit subscriptions", requirement: "20 Knowledge", effect: "Lower monthly burn", status: "available" },
      { id: "sponsor", title: "Sponsor one tool month", requirement: "Funding Hub", effect: "Support badge later", status: "locked" }
    ],
    realityUpdates: ["Season 0: ecosystem needs predictable monthly tool coverage before real scaling."],
    fundingRelationship: "Support can fund operations, but prototype grants no equity or guaranteed return."
  },
  {
    id: "youtube-season-zero",
    slug: "youtube-season-zero",
    name: "YouTube Season 0",
    category: "content",
    owner: "ecosystem",
    status: "planned",
    utilityScore: 640,
    purpose: "Public serial narrative where life updates become episodes, episodes become patch notes and patch notes become missions.",
    realFunction: ["Documents founder journey", "Explains ecosystem decisions", "Creates distribution", "Turns updates into community memory"],
    gameFunction: ["Unlocks Reality Updates", "Boosts Network Power later", "Creates content missions"],
    connectedProductIds: ["youtube", "atlasrepo", "want2view"],
    connectedSubscriptionIds: ["Video tools", "Storage", "Analytics"],
    producedResource: "contribution",
    outputModifier: 3,
    currentLoadPct: 22,
    visualState: "Episode board with empty slots",
    upgradePath: [
      { id: "pilot", title: "Record pilot episode", requirement: "Reality Update", effect: "First content mission", status: "available" },
      { id: "series", title: "Season cadence", requirement: "Network Rank later", effect: "Recurring public missions", status: "locked" }
    ],
    realityUpdates: ["Season 0: YouTube wall exists as the public memory layer."],
    fundingRelationship: "Content can explain funding goals but does not sell investment promises."
  },
  {
    id: "community-signal-map",
    slug: "community-signal-map",
    name: "Community Signal Map",
    category: "community",
    owner: "ecosystem",
    status: "planned",
    utilityScore: 510,
    purpose: "A future reputation map of helpers, testers, creators and early supporters across Telegram and content platforms.",
    realFunction: ["Tracks non-financial help", "Summarizes testing signals", "Connects future partner rooms", "Supports referral design"],
    gameFunction: ["Previews Network City", "Turns helpful actions into Contribution later", "Avoids pure referral farming"],
    connectedProductIds: ["atlasrepo", "want2view", "youtube"],
    connectedSubscriptionIds: ["Telegram", "Analytics"],
    producedResource: "contribution",
    outputModifier: 2,
    currentLoadPct: 0,
    visualState: "Dim network map waiting for verified actions",
    upgradePath: [
      { id: "tester-log", title: "Add tester log", requirement: "Manual review", effect: "Verified community events", status: "locked" },
      { id: "partner-room", title: "Open partner room", requirement: "Partner Marketplace", effect: "Partner tools later", status: "locked" }
    ],
    realityUpdates: ["Season 0: community progress is intentionally locked until abuse controls exist."],
    fundingRelationship: "Community help can earn in-game recognition, not financial yield."
  },
  {
    id: "support-ledger",
    slug: "support-ledger",
    name: "Support Ledger Mock",
    category: "digital",
    owner: "ecosystem",
    status: "funding",
    utilityScore: 390,
    purpose: "Transparent prototype ledger for what supporters would fund: infrastructure, devices, subscriptions, lessons and experiments.",
    realFunction: ["Explains support use", "Separates perks from investments", "Prepares FabricBot requirements"],
    gameFunction: ["Powers Funding Hub preview", "Shows strategy per support goal", "Keeps rewards non-financial"],
    connectedProductIds: ["fabricbot", "atlasrepo"],
    connectedSubscriptionIds: ["Payment provider later", "Accounting later"],
    producedResource: "contribution",
    outputModifier: 1,
    currentLoadPct: 12,
    visualState: "Locked ledger with mock rows",
    upgradePath: [
      { id: "categories", title: "Define support categories", requirement: "Funding Hub spec", effect: "Clear support missions", status: "available" },
      { id: "fabricbot", title: "Connect FabricBot", requirement: "Production Mode", effect: "Real accounting later", status: "locked" }
    ],
    realityUpdates: ["Season 0: all funding data is mock-only until real backend and compliance checks exist."],
    fundingRelationship: "Must stay donation/perk oriented unless legal structure changes."
  }
];
